version: '3.8'

services:
  mysql:
    image: mysql:latest  
    container_name: project-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  #TODO
      MYSQL_DATABASE: project_database
      MYSQL_USER: jtomkus
      MYSQL_PASSWORD: tomkuspass #TODO
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql           
      - ./mysql/init:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:  
  
  #test2